# BEGIN_KITTY_THEME
font_family Maple Mono Italic
background_opacity 0.4
cursor               #AC82E9
map ctrl+c copy_and_clear_or_interrupt
map ctrl+v paste_from_clipboard
# Base2Tone Drawbridge Dark
include current-theme.conf
# END_KITTY_THEME